parameters:
#    century_century.example.class: Century\CenturyBundle\Example

services:
#    century_century.example:
#        class: %century_century.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    guzzle:
        class: GuzzleHttp\Client
        arguments: []
    strava:
        class: StravaApi
        arguments: [%strava_id%, %strava_secret%]
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
        arguments: ~
    century.oauth_user_provider:
        class: Century\CenturyBundle\Auth\OAuthProvider
        arguments: [@doctrine.odm.mongodb.document_manager]
    century.consumer.strava:
        class: Century\CenturyBundle\Consumer\StravaConsumer
        arguments: [@guzzle]
    century.processor.activity:
        class: Century\CenturyBundle\Processor\ActivityProcessor
    century.command.worker.activity:
        class: Century\CenturyBundle\Command\ActivityWorkerCommand
        arguments: [@century.consumer.strava, @century.processor.activity, @century.form.type.activity, @form.factory]
        tags:
            -  { name: console.command }
    century.form.type.activity:
        class: Century\CenturyBundle\Form\Type\ActivityType
        tags:
            - { name: form.type, alias: activity }