parameters:
#    century_century.example.class: Century\CenturyBundle\Example

services:
#    century_century.example:
#        class: %century_century.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    guzzle:
        class: GuzzleHttp\Client
        arguments: []
    strava:
        class: StravaApi
        arguments: [%strava_id%, %strava_secret%]
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
        arguments: ~
    century.oauth_user_provider:
        class: Century\CenturyBundle\Auth\OAuthProvider
        arguments: [@doctrine.odm.mongodb.document_manager]
    century.consumer.strava:
        class: Century\CenturyBundle\Consumer\StravaConsumer
        arguments: [@guzzle, @security.context]