parameters:
#    century_century.example.class: Century\CenturyBundle\Example

services:
#    century_century.example:
#        class: %century_century.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
