parameters:
#    century_century.example.class: Century\CenturyBundle\Example

services:
#    century_century.example:
#        class: %century_century.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    guzzle:
        class: GuzzleHttp\Client
        arguments: []
    strava:
        class: StravaApi
        arguments: [%strava_id%, %strava_secret%]